/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package food.order.service.kotlin.micronaut.app

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }
}
