/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("food.order.service.kotlin.micronaut.kotlin-library-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":common"))
}

